// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package models

import (
	"context"
)

const listCategoriesByStore = `-- name: ListCategoriesByStore :many
SELECT category_id, store_id, name, parent_id, created_at
FROM product_category
WHERE store_id = $1
ORDER BY name
`

func (q *Queries) ListCategoriesByStore(ctx context.Context, storeID int64) ([]ProductCategory, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategory
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(
			&i.CategoryID,
			&i.StoreID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
